"""
fetch_gf_csv.py — Download GF1-GF4 + guidance_tracker CSV files from Drive.
CSVs are pre-generated by Phase 2 and ready for Excel/spreadsheet analysis.

Files downloaded:
  guidance_tracker.csv       — Table A: structured guidance per company/quarter
  gf1_guidance_statements.csv — Raw forward-looking statements
  gf2_historical_guidance.csv — Past guidance vs actual outcomes
  gf3_operational_visibility.csv — Visibility drivers
  gf4_quality_flags.csv      — Guidance quality flags

Usage:
    python scripts/fetch_gf_csv.py            # download all
    python scripts/fetch_gf_csv.py --no-open  # download only, don't open Excel
"""

from __future__ import annotations

import argparse
import io
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload

OUTPUT_DIR = Path(r"D:\EMA_Screener\Reports\signals-india\gf_tables_csv")
SCOPES     = ["https://www.googleapis.com/auth/drive"]

GF_FILES = [
    "guidance_tracker.csv",
    "gf1_guidance_statements.csv",
    "gf2_historical_guidance.csv",
    "gf3_operational_visibility.csv",
    "gf4_quality_flags.csv",
]


def log(msg: str) -> None:
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")


def get_drive():
    load_dotenv(Path(__file__).resolve().parent.parent / ".env")
    tk_json = os.environ.get("GDRIVE_OAUTH_TOKEN_JSON")
    cs_json = os.environ.get("GDRIVE_OAUTH_CLIENT_SECRET_JSON")
    if tk_json and cs_json:
        import json
        creds = Credentials.from_authorized_user_info(json.loads(tk_json), SCOPES)
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
        return build("drive", "v3", credentials=creds, cache_discovery=False)
    tk_path = Path(os.environ["GDRIVE_OAUTH_TOKEN_PATH"])
    creds = None
    if tk_path.exists():
        creds = Credentials.from_authorized_user_file(str(tk_path), SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            from google_auth_oauthlib.flow import InstalledAppFlow
            cs_path = Path(os.environ["GDRIVE_OAUTH_CLIENT_SECRET_PATH"])
            flow = InstalledAppFlow.from_client_secrets_file(str(cs_path), SCOPES)
            creds = flow.run_local_server(port=0)
        tk_path.write_text(creds.to_json())
    return build("drive", "v3", credentials=creds, cache_discovery=False)


def find_subfolder(drive, parent_id: str, name: str) -> str | None:
    q = (f"name='{name}' and '{parent_id}' in parents "
         f"and mimeType='application/vnd.google-apps.folder' and trashed=false")
    files = drive.files().list(q=q, fields="files(id)").execute().get("files", [])
    return files[0]["id"] if files else None


def find_file(drive, folder_id: str, filename: str) -> str | None:
    q = f"name='{filename}' and '{folder_id}' in parents and trashed=false"
    files = drive.files().list(q=q, fields="files(id, modifiedTime)").execute().get("files", [])
    return (files[0]["id"], files[0]["modifiedTime"]) if files else (None, None)


def download_bytes(drive, file_id: str) -> bytes:
    request = drive.files().get_media(fileId=file_id)
    fh = io.BytesIO()
    dl = MediaIoBaseDownload(fh, request)
    done = False
    while not done:
        _, done = dl.next_chunk()
    return fh.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--no-open", action="store_true",
                        help="Download only, don't open in Excel")
    args = parser.parse_args()

    drive     = get_drive()
    folder_id = os.environ["GDRIVE_FOLDER_ID"]

    repo_id  = find_subfolder(drive, folder_id, "company_repo")
    index_id = find_subfolder(drive, repo_id,   "_index") if repo_id else None
    if not index_id:
        log("ERROR: company_repo/_index not found on Drive.")
        sys.exit(1)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    downloaded: list[Path] = []
    missing:    list[str]  = []

    for fname in GF_FILES:
        fid, mtime = find_file(drive, index_id, fname)
        if not fid:
            log(f"  ✗ Not found: {fname}  (Phase 2 hasn't written it yet)")
            missing.append(fname)
            continue

        log(f"Downloading {fname}  (updated {mtime[:10]})…")
        data     = download_bytes(drive, fid)
        out_path = OUTPUT_DIR / fname
        out_path.write_bytes(data)
        kb = len(data) // 1024
        log(f"  ✓ Saved ({kb:.0f} KB): {out_path.name}")
        downloaded.append(out_path)

    print(f"\n  ============================================================")
    print(f"  Downloaded {len(downloaded)}/{len(GF_FILES)} CSV files")
    print(f"  Saved to: {OUTPUT_DIR}")
    if missing:
        print(f"  Missing (not yet generated): {', '.join(missing)}")
    print(f"  ============================================================\n")

    if not args.no_open and downloaded:
        log("Opening folder in Explorer…")
        subprocess.Popen(["explorer", str(OUTPUT_DIR)])


if __name__ == "__main__":
    main()
