"""
notify_deepdive.py — send email when deep-dive reports are ready.

Reads deep_dive_index.parquet from Drive, finds reports completed since
NOTIFY_SINCE (env, ISO datetime) or all reports from today.
Sends one email per report via Gmail SMTP, with the report as a PDF only (falls back
to the styled .html if the PDF cannot be made). The .md/.docx/.pptx stay on Drive.

Required env vars:
    GMAIL_USER         e.g. yourname@gmail.com
    GMAIL_APP_PASSWORD Gmail App Password (not your account password)
    NOTIFY_EMAIL       recipient address

Optional:
    NOTIFY_SINCE       ISO datetime — only email reports newer than this
                       (set automatically by CI step)
    GDRIVE_FOLDER_ID, GDRIVE_OAUTH_TOKEN_JSON  (standard Drive auth)
"""
from __future__ import annotations
import os, io, sys, smtplib, datetime as dt
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import pandas as pd
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)

load_dotenv(os.path.join(os.path.dirname(SCRIPTS_DIR), ".env"))

from daily_research_summary import drive_service, drive_download, _folder_id
from company_deep_report import DRIVE, _read_parquet

GMAIL_USER   = os.environ.get("GMAIL_USER", "")
GMAIL_PASS   = os.environ.get("GMAIL_APP_PASSWORD", "")
NOTIFY_EMAIL = os.environ.get("NOTIFY_EMAIL", GMAIL_USER)
GDRIVE_BASE  = "https://drive.google.com/drive/folders/"
PREVIEW_LINES = 150


def _drive_link(svc, report_path: str, root: str) -> str:
    """Return a best-effort public Drive link for the report file."""
    try:
        # derive parent folder chain
        parts = report_path.rsplit("/", 1)
        folder_path = parts[0] if len(parts) == 2 else ""
        file_name   = parts[-1]
        folder_id   = _folder_id(svc, folder_path, root, create=False)
        if folder_id:
            resp = svc.files().list(
                q=f"'{folder_id}' in parents and name='{file_name}'",
                fields="files(id)", pageSize=1
            ).execute()
            files = resp.get("files", [])
            if files:
                fid = files[0]["id"]
                return f"https://drive.google.com/file/d/{fid}/view"
    except Exception:
        pass
    return f"(Drive path: {report_path})"


def _attach_bytes(msg: MIMEMultipart, data: bytes, filename: str, mime_type: str) -> None:
    part = MIMEBase(*mime_type.split("/", 1))
    part.set_payload(data)
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", "attachment", filename=filename)
    msg.attach(part)


def _build_email(name: str, symbol: str, isin: str,
                 report_md: str, drive_link: str) -> MIMEMultipart:
    preview = "\n".join(report_md.splitlines()[:PREVIEW_LINES])
    subject = f"Deep Dive Ready: {name} ({symbol})"
    # PDF ONLY (user 2026-10-02: the .md arrived unformatted; .md / .docx / .pptx stay on
    # Drive). If the PDF cannot be made, say so and attach the same styled page as .html.
    # File name = company _ report type _ date (format_deepdive_pdf.report_basename).
    import format_deepdive_pdf as FMT
    slug    = FMT.report_basename(name, "DeepDive")
    attach, note = None, ""
    try:
        attach = (f"{slug}.pdf", FMT.md_to_pdf(report_md, name, symbol, isin),
                  "application/pdf")
    except Exception as e:
        print(f"  pdf generation FAILED ({e}) — attaching .html instead")
        note = (f"<p style='color:#c33'><b>PDF could not be made</b> ({str(e)[:120]}) — "
                f"the report is attached as .html instead.</p>")
        attach = (f"{slug}.html",
                  FMT._build_full_html(name, symbol, isin, report_md).encode("utf-8"),
                  "text/html")

    # Formatted preview (the same markdown->HTML the PDF uses), not raw markdown text.
    try:
        html_preview = FMT._md_to_html_body(preview)
    except Exception:
        html_preview = "<pre>" + preview.replace("<", "&lt;") + "</pre>"
    html_body = f"""
<html><body>
<p><b>Deep dive report generated for <span style="color:#1a1a2e">{name}</span>
({symbol} / {isin})</b></p>
<p>📄 <a href="{drive_link}">Open on Google Drive</a></p>
<p style="font-size:11px;color:#666">Attachment: {attach[0]}</p>
{note}
<hr>
<div style="font-size:13px;color:#333">{html_preview}</div>
<hr>
<p style="font-size:11px;color:#999">Generated by signals-india deepdive pipeline ·
{dt.datetime.now():%Y-%m-%d %H:%M}</p>
</body></html>"""

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"]    = GMAIL_USER
    msg["To"]      = NOTIFY_EMAIL

    # body (plain + html alternative)
    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(preview, "plain"))
    alt.attach(MIMEText(html_body, "html"))
    msg.attach(alt)

    _attach_bytes(msg, attach[1], attach[0], attach[2])
    return msg


def _both_pending(svc, root) -> set[str]:
    """Upper-cased tokens of narrative_queue rows still PENDING for BOTH reports
    (with_deepdive) — their deep dive is emailed with the story. Empty on any error, so a
    queue read problem can only mean an extra email, never a lost one."""
    try:
        q = _read_parquet(svc, "company_repo/_index/narrative_queue.parquet", root)
        if q.empty or "with_deepdive" not in q.columns:
            return set()
        wd = q["with_deepdive"].map(lambda v: v is True or str(v).lower() == "true")
        p = q[(q["status"].astype(str) == "pending") & wd]
        return {str(t).strip().upper() for t in p["token"]}
    except Exception:
        return set()


def send_notifications(report_isins: list[str] | None = None):
    if not GMAIL_USER or not GMAIL_PASS:
        print("notify_deepdive: GMAIL_USER / GMAIL_APP_PASSWORD not set — skipping email."); return

    svc  = drive_service()
    root = os.environ.get("GDRIVE_FOLDER_ID", "")
    idx  = _read_parquet(svc, DRIVE["index"], root)

    if idx.empty:
        print("notify_deepdive: deep_dive_index is empty."); return

    # filter to requested ISINs or today's reports
    since_str = os.environ.get("NOTIFY_SINCE", "")
    if report_isins:
        rows = idx[idx["isin"].isin(report_isins)]
    elif since_str:
        since = dt.datetime.fromisoformat(since_str)
        rows = idx[pd.to_datetime(idx["last_update"]) >= since]
    else:
        today = dt.date.today().isoformat()
        rows = idx[idx["last_update"].astype(str).str.startswith(today)]

    # ONE email per company for BOTH (user 2026-10-04): a company still waiting in
    # narrative_queue for BOTH reports gets its deep dive inside the STORY email (both
    # PDFs) — skip it here. An explicit report_isins list (the story-failed fallback) is
    # never skipped.
    if not report_isins:
        both = _both_pending(svc, root)
        if both:
            keys = rows.apply(lambda r: {str(r.get(c, "")).strip().upper()
                                         for c in ("isin", "symbol", "name")}, axis=1)
            skip = keys.map(lambda k: bool(k & both))
            for _, r in rows[skip].iterrows():
                print(f"  held for the story email (BOTH queued): {r.get('name', r.get('isin'))}")
            rows = rows[~skip]

    if rows.empty:
        print("notify_deepdive: no reports to notify."); return

    sent = 0
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(GMAIL_USER, GMAIL_PASS)
        for _, row in rows.iterrows():
            try:
                report_path = row.get("report_path", "")
                raw = drive_download(svc, report_path, root) if report_path else None
                report_md = raw.decode("utf-8") if raw else "(report could not be fetched)"
                link = _drive_link(svc, report_path, root) if report_path else ""
                msg  = _build_email(
                    str(row.get("name", row.get("isin", ""))),
                    str(row.get("symbol", "")),
                    str(row.get("isin", "")),
                    report_md, link)
                smtp.send_message(msg)
                print(f"  emailed: {row.get('name','')} -> {NOTIFY_EMAIL}")
                sent += 1
            except Exception as e:
                print(f"  email failed for {row.get('isin','')}: {e}")

    print(f"notify_deepdive: {sent} email(s) sent.")


if __name__ == "__main__":
    # optional: pass ISINs as CLI args to notify specific companies
    isins = sys.argv[1:] if len(sys.argv) > 1 else None
    send_notifications(isins)
